/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useGLTF} from "@react-three/drei";

export default function Macbook(props) {
  const {scene} = useGLTF("/models/macbook/model.gltf");
  return <primitive object={scene} {...props} />;
}

useGLTF.preload("/models/macbook/model.gltf");
