/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import {useGLTF} from "@react-three/drei";

export function CoffeeCupModel(props) {
  const {nodes, materials} = useGLTF("/models/coffee_cup/coffee_cup.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.wood_desk.geometry}
        material={materials["Light tree wood"]}
      />
      <mesh castShadow={true} receiveShadow={true} geometry={nodes.柱体002.geometry} material={materials.材质}/>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.柱体002_1.geometry}
        material={materials["材质.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/coffee_cup/coffee_cup.gltf");
