/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import {useGLTF, useTexture} from "@react-three/drei";
import {DoubleSide} from "three";

export default function TransferArrayModel(props) {
  const {nodes, materials} = useGLTF("/models/transfer_array/transfer_array.gltf");
  console.log("materials", materials);

  // load baked textures
  const bakedTexture = useTexture("/models/transfer_array/bake.jpg");
  bakedTexture.flipY = false;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.ground.geometry}
      >
        <meshBasicMaterial map={bakedTexture}/>
      </mesh>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.stump.geometry}
        position={[1.829, -0.035, 1.408]}
      >
        <meshBasicMaterial map={bakedTexture}/>
      </mesh>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.lampstandard.geometry}
        position={[1.457, 0.742, -1.242]}
      >
        <meshBasicMaterial map={bakedTexture}/>
      </mesh>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.transfer.geometry}
        position={[0, -0.154, -2.024]}
      >
        <meshBasicMaterial map={bakedTexture}/>
      </mesh>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.wood_labels.geometry}
        position={[1.041, 0.337, -1.102]}
        rotation={[0, -1.494, 0]}
      >
        <meshBasicMaterial map={bakedTexture}/>
      </mesh>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.stones.geometry}
        position={[-2.21, -0.098, 1.092]}
        rotation={[0, -1.45, 0]}
      >
        <meshBasicMaterial map={bakedTexture}/>
      </mesh>

      // light
      <mesh position={[1.05, 1.24, -1.25]}>
        <boxGeometry args={[0.16, 0.16, 0.16]}/>
        <meshBasicMaterial color="white" toneMapped={false}/>
      </mesh>
      <mesh position={[1.05, 1.24, 2.12]}>
        <boxGeometry args={[0.16, 0.16, 0.16]}/>
        <meshBasicMaterial color="white" toneMapped={false}/>
      </mesh>
      <mesh position={[-0.8, 1.24, 2.07]}>
        <boxGeometry args={[0.16, 0.16, 0.16]}/>
        <meshBasicMaterial color="white" toneMapped={false}/>
      </mesh>
      <mesh position={[-0.8, 1.24, -1.21]}>
        <boxGeometry args={[0.16, 0.16, 0.16]}/>
        <meshBasicMaterial color="white" toneMapped={false}/>
      </mesh>

      // transfer array
      <mesh position={[0, 0.5, -2.1]}>
        // 圆平面
        <circleGeometry args={[0.92, 32]}/>
        <meshBasicMaterial color={[2, 0, 2]} toneMapped={false}/>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/transfer_array/transfer_array.gltf");
